### ISSUE TITLE
Unable to retrieve schema - Flatfile

### ISSUE THREAD

**Issue by remv** [Microsoft/MIMPowerShellConnectors#5]
I tried setting up the Flat file connector using the latest MIM Powershell MA. When done configuring "Capabilities" I get an error retrieving the schema:

![image](https://cloud.githubusercontent.com/assets/4202139/15958056/8249723a-2ef3-11e6-96e9-10abeb6e0c8a.png)

The event log outputs the following:

```
The extensible extension returned an unsupported error.
 The stack trace is:

 "Microsoft.MetadirectoryServices.ExtensionException: The Schema returned from the PowerShell compliant server is null
   at Microsoft.IdentityManagement.Connector.PowerShell.Bridge.ConfigBridge.GetSchema()
Forefront Identity Manager 4.3.1935.0"
```

**Comment by jkovach82** [comment]
What is missing in the instructions is you need to copy ALL of the contents of the FlatFileConnector files to the Extensions directory, this includes the 3 scripts...one of which retrieves the schema from the Sample.txt file.

**Comment by jkovach82** [comment]
Finally got the schema to load.  I turned on detailed logging and noticed there was an error in the schema script.  The whole script must be parsed and loaded into memory before execution can occur.

Runtime exception occurred System.Management.Automation.ParseException: At C:\Windows\TEMP\mbgwd3ci.ps1:2 char:55
- [Syste

and 

Runtime exception occurred System.Management.Automation.ParseException: At C:\Windows\TEMP\otpqui3o.ps1:2 char:106
- ... o

Since there were two different errors I was sure it was that param function however was unsure of the proper syntax.  Since the xADSyncPSConnectorModule.psm1 seemed to load without errors I looked to see if there was another example of what the syntax should be and found it should look like this:

param( 
        _[System.Collections.ObjectModel.KeyedCollection[[string], [Microsoft.MetadirectoryServices.ConfigParameter]]]
        $ConfigurationParameters_,
        [PSCredential] 
    $PSCredential
)

**Comment by jkovach82** [comment]
Not sure if this made a difference either but there are two different versions of the MIM PowerShell connector floating around use version 4.3.1082.0.  Make sure use the latest one with the file size 1,176 KB not 1,212 KB that was bundled with all the other connectors.

**Comment by bdesmond** [comment]
I just checked in a fix to the typo you found. Let me know if that helps.

**Comment by jkovach82** [comment]
Fixed a few more syntax errors in the Import script but still cannot create the new management agent.  I get all the way to the last screen and the get an error.  This is what is displayed in the Application log:

The server encountered an unexpected error while performing an operation for the client.

 "BAIL: MMS(8780): ..\cdext.cpp(416): 0x80070057 (The parameter is incorrect.)
BAIL: MMS(8780): ..\xstack.cpp(405): 0x80070057 (The parameter is incorrect.)
BAIL: MMS(8780): ..\xparse.cpp(436): 0x80070057 (The parameter is incorrect.)
BAIL: MMS(8780): ..\schema.cpp(1619): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\compmap.cpp(155): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\compmap.cpp(453): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\xsimple.cpp(842): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\xstack.cpp(540): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\xparse.cpp(544): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\xsimple.cpp(334): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\compmap.cpp(344): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\mastate.cpp(10654): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
ERR_: MMS(8780): ..\mastate.cpp(13153): Error creating MA component mappings object: 0x80230914
BAIL: MMS(8780): ..\mastate.cpp(13173): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\mastate.cpp(1724): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
BAIL: MMS(8780): ..\server.cpp(1078): 0x80230914 (E_MMS_SCHEMA_CLASS_NOT_FOUND)
Forefront Identity Manager 4.3.2195.0"

**Comment by jkovach82** [comment]
Fixed my own issue here... appears that the PowerShell 4.3.1082.0 is missing the Global Parameters section at the bottom of the list: File name, Delimeter and Encoding.  I installed the 1.1.117.0 version and now I have my new connector!

**Comment by jkovach82** [comment]
Another thing I just noticed is that the SampleInputFile.txt must have at least 2 rows, the header and another sample row under that for the schema to import.

**Comment by alvaradojl** [comment]
Any updates on this issue? I'm still having the same problem!

**Comment by steffied** [comment]
Fixed by adjusting the schema as suggested! Thanks
**param(
[System.Collections.ObjectModel.KeyedCollection[[string], [Microsoft.MetadirectoryServices.ConfigParameter]]]
$ConfigurationParameters,
[PSCredential]
$PSCredential
)**

**Comment by NileshGhodekar** [comment]
closing as the updated script with typo fixed was checked in by Brian.
